import { spawnSync } from "node:child_process";
import { mkdtempSync, readdirSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const projectDir = resolve(__dirname, "..");
const featureProjectDir = join(
  projectDir,
  "src/universal/.devcontainer/features"
);
const featureSourceDir = join(featureProjectDir, "src");
const devcontainer = join(projectDir, "node_modules/.bin/devcontainer");
const internalFeatures = new Set(["test-base"]);
const testContainerLabel = "devcontainer.is_test_run=true";

const availableFeatures = readdirSync(featureSourceDir, { withFileTypes: true })
  .filter(
    (entry) =>
      entry.isDirectory() &&
      !entry.name.startsWith("_") &&
      !internalFeatures.has(entry.name)
  )
  .map((entry) => entry.name)
  .sort();

const requestedArguments = process.argv.slice(2);
const runAll = requestedArguments.includes("--all");
const requestedFeatures = requestedArguments.filter(
  (argument) => argument !== "--all"
);

function fail(message) {
  console.error(message);
  console.error(`Available features: ${availableFeatures.join(", ")}`);
  process.exitCode = 1;
}

function runDocker(args, options = {}) {
  return spawnSync("docker", args, {
    cwd: projectDir,
    encoding: "utf8",
    ...options,
  });
}

function dockerOutput(args) {
  const result = runDocker(args);

  if (result.error || result.status !== 0) {
    throw new Error(
      `Docker command failed: ${result.error?.message ?? result.stderr.trim()}`
    );
  }

  return result.stdout.trim();
}

function removeResources(type, resourceIds) {
  if (resourceIds.length === 0) return;

  console.log(`(*) Removing ${resourceIds.length} test ${type}(s)...`);
  const result = runDocker([type, "rm", "-f", ...resourceIds], {
    stdio: "inherit",
  });

  if (result.error || result.status !== 0) {
    throw new Error(`Failed to remove Docker ${type}(s).`);
  }
}

function listTestContainers(testRunDir) {
  const output = dockerOutput([
    "container",
    "ls",
    "-a",
    "--filter",
    `label=${testContainerLabel}`,
    "--format",
    '{{.ID}}\t{{.Label "devcontainer.local_folder"}}',
    "--no-trunc",
  ]);

  return output
    .split("\n")
    .filter(Boolean)
    .map((line) => line.split("\t"))
    .filter(([, workspace]) => workspace?.startsWith(`${testRunDir}/`))
    .map(([id]) => id);
}

function listTestImages(testRunDir) {
  const workspaceRoot = join(
    testRunDir,
    "devcontainercli/container-features-test"
  );

  try {
    return readdirSync(workspaceRoot, { withFileTypes: true })
      .filter((entry) => entry.isDirectory())
      .flatMap((entry) =>
        dockerOutput([
          "image",
          "ls",
          "-a",
          "--filter",
          `reference=vsc-${entry.name}-*-features*`,
          "-q",
          "--no-trunc",
        ])
          .split(/\s+/)
          .filter(Boolean)
      );
  } catch (error) {
    if (error?.code === "ENOENT") return [];
    throw error;
  }
}

function cleanupTestResources(testRunDir) {
  let failed = false;

  for (const [type, listResources] of [
    ["container", listTestContainers],
    ["image", listTestImages],
  ]) {
    try {
      removeResources(type, [...new Set(listResources(testRunDir))]);
    } catch (error) {
      console.error(error instanceof Error ? error.message : String(error));
      failed = true;
    }
  }

  return !failed;
}

if (runAll && requestedFeatures.length > 0) {
  fail("'--all' cannot be combined with feature names.");
} else if (!runAll && requestedFeatures.length === 0) {
  fail("Usage: pnpm test:feature <feature...>");
} else {
  const unknownFeatures = requestedFeatures.filter(
    (feature) => !availableFeatures.includes(feature)
  );

  if (unknownFeatures.length > 0) {
    fail(`Unknown feature(s): ${unknownFeatures.join(", ")}`);
  } else {
    const args = [
      "features",
      "test",
      "--project-folder",
      featureProjectDir,
      "--skip-autogenerated",
      "--skip-duplicated",
      "--preserve-test-containers",
    ];

    const selectedFeatures = runAll ? availableFeatures : requestedFeatures;
    args.push("--features", ...selectedFeatures);

    console.log(
      `(*) Testing ${runAll ? "all features" : requestedFeatures.join(", ")}...`
    );
    console.log(`\n$ ${devcontainer} ${args.join(" ")}`);

    const testRunDir = mkdtempSync(join(tmpdir(), "sl-feature-test-"));

    try {
      const result = spawnSync(devcontainer, args, {
        cwd: projectDir,
        env: { ...process.env, TMPDIR: testRunDir },
        stdio: "inherit",
      });

      if (result.error) {
        console.error(`Failed to start Dev Container CLI: ${result.error.message}`);
        process.exitCode = 1;
      } else {
        process.exitCode = result.status ?? 1;
      }
    } finally {
      if (!cleanupTestResources(testRunDir)) {
        process.exitCode = 1;
      }
      rmSync(testRunDir, { recursive: true, force: true });
    }
  }
}
