import { spawnSync } from "node:child_process";
import { readdirSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const projectDir = resolve(__dirname, "..");
const featureProjectDir = join(
  projectDir,
  "src/universal/.devcontainer/features"
);
const featureSourceDir = join(featureProjectDir, "src");
const devcontainer = join(projectDir, "node_modules/.bin/devcontainer");
const internalFeatures = new Set(["test-base"]);

const availableFeatures = readdirSync(featureSourceDir, { withFileTypes: true })
  .filter(
    (entry) =>
      entry.isDirectory() &&
      !entry.name.startsWith("_") &&
      !internalFeatures.has(entry.name)
  )
  .map((entry) => entry.name)
  .sort();

const requestedArguments = process.argv.slice(2);
const runAll = requestedArguments.includes("--all");
const requestedFeatures = requestedArguments.filter(
  (argument) => argument !== "--all"
);

function fail(message) {
  console.error(message);
  console.error(`Available features: ${availableFeatures.join(", ")}`);
  process.exitCode = 1;
}

if (runAll && requestedFeatures.length > 0) {
  fail("'--all' cannot be combined with feature names.");
} else if (!runAll && requestedFeatures.length === 0) {
  fail("Usage: pnpm test:feature <feature...>");
} else {
  const unknownFeatures = requestedFeatures.filter(
    (feature) => !availableFeatures.includes(feature)
  );

  if (unknownFeatures.length > 0) {
    fail(`Unknown feature(s): ${unknownFeatures.join(", ")}`);
  } else {
    const args = [
      "features",
      "test",
      "--project-folder",
      featureProjectDir,
      "--skip-autogenerated",
      "--skip-duplicated",
    ];

    const selectedFeatures = runAll ? availableFeatures : requestedFeatures;
    args.push("--features", ...selectedFeatures);

    console.log(
      `(*) Testing ${runAll ? "all features" : requestedFeatures.join(", ")}...`
    );
    console.log(`\n$ ${devcontainer} ${args.join(" ")}`);

    const result = spawnSync(devcontainer, args, {
      cwd: projectDir,
      stdio: "inherit",
    });

    if (result.error) {
      console.error(`Failed to start Dev Container CLI: ${result.error.message}`);
      process.exitCode = 1;
    } else {
      process.exitCode = result.status ?? 1;
    }
  }
}
